@startuml PlayerLogicState
state "PlayerLogicState" as KitchenChaos_PlayerLogicState {
  state "Alive" as KitchenChaos_PlayerLogicState_Alive {
    state "Grounded" as KitchenChaos_PlayerLogicState_Grounded {
      state "Idle" as KitchenChaos_PlayerLogicState_Idle
      state "Interacting" as KitchenChaos_PlayerLogicState_Interacting
      state "Moving" as KitchenChaos_PlayerLogicState_Moving
      state "PickingUp" as KitchenChaos_PlayerLogicState_PickingUp
    }
  }
  state "Dead" as KitchenChaos_PlayerLogicState_Dead
  state "Disabled" as KitchenChaos_PlayerLogicState_Disabled
}

KitchenChaos_PlayerLogicState_Alive --> KitchenChaos_PlayerLogicState_Alive : FacingCounterChanged
KitchenChaos_PlayerLogicState_Alive --> KitchenChaos_PlayerLogicState_Alive : Moved
KitchenChaos_PlayerLogicState_Alive --> KitchenChaos_PlayerLogicState_Alive : PhysicsTick
KitchenChaos_PlayerLogicState_Alive --> KitchenChaos_PlayerLogicState_Alive : Pushed
KitchenChaos_PlayerLogicState_Alive --> KitchenChaos_PlayerLogicState_Dead : Killed
KitchenChaos_PlayerLogicState_Disabled --> KitchenChaos_PlayerLogicState_Idle : Enable
KitchenChaos_PlayerLogicState_Idle --> KitchenChaos_PlayerLogicState_Idle : InteractionStarted
KitchenChaos_PlayerLogicState_Idle --> KitchenChaos_PlayerLogicState_Interacting : InteractionStarted
KitchenChaos_PlayerLogicState_Idle --> KitchenChaos_PlayerLogicState_Moving : StartedMovingHorizontally
KitchenChaos_PlayerLogicState_Interacting --> KitchenChaos_PlayerLogicState_Idle : InteractionCompleted
KitchenChaos_PlayerLogicState_Moving --> KitchenChaos_PlayerLogicState_Idle : StoppedMovingHorizontally
KitchenChaos_PlayerLogicState_PickingUp --> KitchenChaos_PlayerLogicState_Idle : PickUpCompleted

KitchenChaos_PlayerLogicState_Alive : OnPhysicsTick → MovementComputed
KitchenChaos_PlayerLogicState_Alive : OnPushed → VelocityChanged
KitchenChaos_PlayerLogicState_Disabled : OnEnter → Idle
KitchenChaos_PlayerLogicState_Idle : OnEnter → Idle
KitchenChaos_PlayerLogicState_Moving : OnEnter → Move
KitchenChaos_PlayerLogicState_PickingUp : OnEnter → KitchenObjectChanged
@enduml