@startuml

package App-Type [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs]] {
    class App  {
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs ScriptFile]]
        [Properties]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:79 AnimationPlayer]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:70 AppBinding]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:68 AppLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/AppLogic.Data.cs Script]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:67 AppRepo]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:78 BlankScreen]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:34 Game]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs Script]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:77 GamePreview]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:35 Instantiator]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/utils/Instantiator.cs Script]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:76 Menu]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs Script]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:41 SaveFile]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:80 Splash]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs Script]]
        --
        [Methods]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:24 _Notification()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:234 DeleteSaveFile()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:179 FadeInFromBlack()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:185 FadeToBlack()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:191 HideMenus()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:84 Initialize()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:223 LoadSaveFile()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:163 OnAnimationFinished()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:161 OnDeleteGame()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:197 OnExitTree()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:159 OnLoadGame()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:157 OnNewGame()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:103 OnReady()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/app/App.cs:211 ShowMainMenu()]]
    }
    package Game-Type [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs]] {
        class Game  {
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs ScriptFile]]
            [Properties]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:27 EntityTable]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:51 GameBinding]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:49 GameLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs Script]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:48 GameRepo]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:59 Map]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs Script]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:58 Player]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs Script]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:57 PlayerCamera]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs Script]]
            --
            [Methods]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:157 _Input()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:20 _Notification()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:37 Load()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:186 OnExitTree()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:165 OnMainMenu()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:180 OnPauseMenuSaveRequested()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:177 OnPauseMenuTransitioned()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:99 OnResolved()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:168 OnResume()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:171 OnStart()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:30 Save()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:201 SaveGame()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:207 SetPauseMode()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/Game.cs:79 Setup()]]
        }
        class GameLogic  {
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs ScriptFile]]
            [Constructors]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs:18 GameLogic]]()
            --
            [Methods]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs:31 OnStart()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs:23 OnStartSubscriptions()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/game/GameLogic.cs:40 OnStop()]]
        }
        class Map  {
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs ScriptFile]]
            [Properties]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:91 MapLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/MapLogic.Data.cs Script]]
            --
            [Methods]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:21 _Notification()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:47 Load()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:99 OnResolved()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:29 Save()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/map/Map.cs:97 Setup()]]
        }
        class Player  {
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs ScriptFile]]
            [Provisions]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:110 IPlayerLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/PlayerLogic.Settings.cs Script]]
            --
            [Interface Properties]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:161 PlayerLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/PlayerLogic.Settings.cs Script]]
            [Properties]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:143 Acceleration]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:66 CarryingPosition]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:327 CenterOfMass]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:57 CounterRayCast3D]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:54 FollowVisualRotation]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:135 Gravity]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:154 JumpForce]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:147 JumpImpulseForce]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:139 MoveSpeed]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:164 PlayerBinding]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:127 RotationSpeed]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:162 Settings]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:131 StoppingSpeed]]
            --
            [Interface Methods]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:275 GetGlobalInputVector()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:291 GetNextRotationBasis()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:312 IsMovingHorizontally()]]
            [Methods]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:50 _Notification()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:73 Carry()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:80 Drop()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:82 GetKitchenObject()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:81 HasKitchenObject()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:333 Kill()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:98 Load()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:193 OnExitTree()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:234 OnPhysicsProcess()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:191 OnReady()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:200 OnResolved()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:320 Push()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:91 Save()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:168 Setup()]]
            [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player/Player.cs:270 ShouldJump()]]
        }
        package PlayerCamera-Type [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs]] {
            class PlayerCamera  {
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs ScriptFile]]
                [Interface Properties]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:130 CameraBasis]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:126 CameraLocalPosition]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:91 CameraLogic]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraLogic.Data.cs Script]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:127 GimbalRotationHorizontal]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:128 GimbalRotationVertical]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:99 Offset]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:133 OffsetPosition]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:125 SpringArmTargetPosition]]
                [Properties]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:93 CameraBinding]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:116 CameraNode]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:110 GimbalHorizontalNode]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:113 GimbalVerticalNode]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:108 OffsetNode]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:101 Settings]] - [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs Script]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:118 SpringArmTarget]]
                --
                [Interface Methods]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:209 UsePlayerCamera()]]
                [Methods]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:201 _Input()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:63 _Notification()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:75 Load()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:211 OnExitTree()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:178 OnPhysicsProcess()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:156 OnResolved()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:67 Save()]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCamera.cs:137 Setup()]]
            }
            class PlayerCameraSettings  {
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs ScriptFile]]
                [Properties]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs:11 JoypadSensitivity]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs:8 MouseSensitivity]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs:17 VerticalMax]]
                [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/player_camera/PlayerCameraSettings.cs:23 VerticalMin]]
            }
            PlayerCamera::PlayerCameraSettings ---> PlayerCameraSettings
        }
        Game::GameLogic ---> GameLogic
        Game::Map ---> Map
        Game::Player ---> Player
        Game::PlayerCamera ---> PlayerCamera
    }
    class Instantiator  {
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/utils/Instantiator.cs ScriptFile]]
        [Interface Properties]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/utils/Instantiator.cs:27 SceneTree]]
        --
        [Interface Methods]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/utils/Instantiator.cs:34 LoadAndInstantiate()]]
    }
    class Menu  {
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs ScriptFile]]
        [Properties]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:27 DeleteGameButton]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:25 LoadGameButton]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:23 NewGameButton]]
        --
        [Interface Methods]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:58 SetGameExists()]]
        [Methods]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:20 _Notification()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:56 OnDeleteGamePressed()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:47 OnExitTree()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:55 OnLoadGamePressed()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:54 OnNewGamePressed()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/Menu.cs:40 OnReady()]]
    }
    class Splash  {
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs ScriptFile]]
        [Properties]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:16 AnimationPlayer]]
        --
        [Methods]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:34 _Input()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:13 _Notification()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:31 OnAnimationFinished()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:28 OnExitTree()]]
        [[vscode://file/C:/Users/maxim/Documents/Godot/KitchenChaos/src/menu/splash/Splash.cs:25 OnReady()]]
    }
    App::Game ---> Game
    App::Instantiator ---> Instantiator
    App::Menu ---> Menu
    App::Splash ---> Splash
}

@enduml