@startuml PlayerCameraLogicState
state "PlayerCameraLogicState" as KitchenChaos_PlayerCameraLogicState {
  state "InputDisabled" as KitchenChaos_PlayerCameraLogicState_InputDisabled
  state "InputEnabled" as KitchenChaos_PlayerCameraLogicState_InputEnabled
}

KitchenChaos_PlayerCameraLogicState --> KitchenChaos_PlayerCameraLogicState : PhysicsTicked
KitchenChaos_PlayerCameraLogicState --> KitchenChaos_PlayerCameraLogicState : TargetOffsetChanged
KitchenChaos_PlayerCameraLogicState --> KitchenChaos_PlayerCameraLogicState : TargetPositionChanged
KitchenChaos_PlayerCameraLogicState_InputDisabled --> KitchenChaos_PlayerCameraLogicState_InputEnabled : EnableInput
KitchenChaos_PlayerCameraLogicState_InputEnabled --> KitchenChaos_PlayerCameraLogicState_InputDisabled : DisableInput
KitchenChaos_PlayerCameraLogicState_InputEnabled --> KitchenChaos_PlayerCameraLogicState_InputEnabled : JoyPadInputOccurred
KitchenChaos_PlayerCameraLogicState_InputEnabled --> KitchenChaos_PlayerCameraLogicState_InputEnabled : MouseInputOccurred

KitchenChaos_PlayerCameraLogicState : OnPhysicsTicked → CameraLocalPositionChanged, CameraOffsetChanged, GimbalRotationChanged, GlobalTransformChanged
@enduml