@startuml PlayerCameraLogicState
state "PlayerCameraLogicState" as ChickenChaos_PlayerCameraLogicState {
  state "InputDisabled" as ChickenChaos_PlayerCameraLogicState_InputDisabled
  state "InputEnabled" as ChickenChaos_PlayerCameraLogicState_InputEnabled
}

ChickenChaos_PlayerCameraLogicState --> ChickenChaos_PlayerCameraLogicState : PhysicsTicked
ChickenChaos_PlayerCameraLogicState --> ChickenChaos_PlayerCameraLogicState : TargetOffsetChanged
ChickenChaos_PlayerCameraLogicState --> ChickenChaos_PlayerCameraLogicState : TargetPositionChanged
ChickenChaos_PlayerCameraLogicState_InputDisabled --> ChickenChaos_PlayerCameraLogicState_InputEnabled : EnableInput
ChickenChaos_PlayerCameraLogicState_InputEnabled --> ChickenChaos_PlayerCameraLogicState_InputDisabled : DisableInput
ChickenChaos_PlayerCameraLogicState_InputEnabled --> ChickenChaos_PlayerCameraLogicState_InputEnabled : JoyPadInputOccurred
ChickenChaos_PlayerCameraLogicState_InputEnabled --> ChickenChaos_PlayerCameraLogicState_InputEnabled : MouseInputOccurred

ChickenChaos_PlayerCameraLogicState : OnPhysicsTicked → CameraLocalPositionChanged, CameraOffsetChanged, GimbalRotationChanged, GlobalTransformChanged
@enduml